metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.0.3.5, mac: 'ea:0b:9f:15:c5:2b', disk: xvda, network_interface: eth0}
        metal1: {ansible_host: 10.0.3.6, mac: '6a:76:9e:c5:d1:90', disk: xvda, network_interface: eth0}
        metal2: {ansible_host: 10.0.3.7, mac: 'de:e4:60:9e:fe:79', disk: xvda, network_interface: eth0}
    workers:
      hosts:
        metal3: {ansible_host: 10.0.3.8, mac: 'fa:44:34:2d:90:24', disk: xvda, network_interface: eth0}
        metal4: {ansible_host: 10.0.3.9, mac: 'd6:fd:64:f2:99:01', disk: xvda, network_interface: eth0}
